"""empty message

Revision ID: 3efc8bec5724
Revises: b1dc628a2dcb
Create Date: 2024-12-21 21:32:15.634076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efc8bec5724'
down_revision = 'b1dc628a2dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('food_image', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
