"""empty message

Revision ID: e66bdbf02ac3
Revises: 4489d6ed903e
Create Date: 2024-12-21 18:31:46.193994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66bdbf02ac3'
down_revision = '4489d6ed903e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('pantry_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pantry_item_id'], ['pantry_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=256), nullable=True))

    op.drop_table('food_image')
    # ### end Alembic commands ###
